### ISSUE TITLE
Support for time locale?

### ISSUE THREAD

**Issue by rayita** [IliaIdakiev/angular-material-timepicker#20]
As far I can see locale support is limited to 24h/12h format with a hardcoded time format in 12h mode of  "HH:mm [a|am|p|pm]" but not in all languages/country use am/pm.

Can you take a look to this improvement?

Thanks.

**Comment by IliaIdakiev** [comment]
Thanks for opening this issue. No problem, I will add an input for the meridiem abbreviations. I will close the issue after it's done.

**Comment by IliaIdakiev** [comment]
Added anteMeridiemAbbreviation and postMeridiemAbbreviation inputs 
8d773e3
