### ISSUE TITLE
bug(timepicker) Won't set selected current time

### ISSUE THREAD

**Issue by Totati** [IliaIdakiev/angular-material-timepicker#21]
Hello, there's a bug, when opening the timepicker with null value, it seems that the current time is selected, but clicking OK won't set the value, and leaves the control empty. [Stackblitz DEMO](https://stackblitz.com/edit/mat-timepicker-current-time)

**Comment by IliaIdakiev** [comment]
Hello, thanks for opening this issue. I will resolve the problem later today and I will close the issue after that.

**Comment by Totati** [comment]
@IliaIdakiev I've found a similar bug 😅When I use the timepicker as a standalone input without model, focusout sets undefined as the the text of the nativeElement.value. https://github.com/IliaIdakiev/angular-material-timepicker/blob/8d773e3e759facac87f4472e1acc6cb8a07703e3/projects/mat-timepicker/src/lib/timepicker.directive.ts#L386

I've updated the stackblitz example. I'm using a model less timepicker, and updating a control behind a datepicker.

**Comment by IliaIdakiev** [comment]
bf5f8ee - mat-timepicker@4.1.2

**Comment by IliaIdakiev** [comment]
@Totati I hope everything is working as expected now? If so would you mind star-ing the library, thanks.

**Comment by Totati** [comment]
@IliaIdakiev The closing bug it now gone, it works fine, however the undefined value still occurs. [Example](https://stackblitz.com/edit/mat-timepicker-current-time-rfy2w4)

**Comment by IliaIdakiev** [comment]
Fixed @ 4.1.4
