### ISSUE TITLE
Add install documentation

### ISSUE THREAD

**Issue by Pato2790** [IliaIdakiev/angular-material-timepicker#28]
Hi man!

I really like your timepicker, but I didn't see the install documentation in the readme. Just add you npm page because the project in npm and the repository name are diferent!

https://www.npmjs.com/package/mat-timepicker

Thanks you Bro!

**Comment by IliaIdakiev** [comment]
Hello @Pato2790 ! Thanks for opening this issue. I'm not sure why I haven't added that, maybe when I was updating the Readme I removed it by mistake but anyways ... thanks I've just added it to the readme 6235e1e

I would appreciate if you start the repo if you like it :) Thanks!
