### ISSUE TITLE
In Mozilla Firefox mousemove triggers time selection even without clicking and holding.

### ISSUE THREAD

**Issue by Totati** [IliaIdakiev/angular-material-timepicker#31]
In Firefox 79.0 (64-bit) hovering a time selects it automatically. It seems this is due to MouseEvent.which always equals 1. https://github.com/IliaIdakiev/angular-material-timepicker/blob/6235e1e85e8d6938a64d8112990568ffef03a8e6/projects/mat-timepicker/src/lib/clock/clock.component.ts#L152

**Comment by Levon770** [comment]
I have same problem, 
The current version of "mat-timepicker" is 4.1.10
and Firefox version is 79.0 64bit

**Comment by IliaIdakiev** [comment]
Hello guys. I will look into it this week. Thanks for opening this issue.

**Comment by IliaIdakiev** [comment]
@Totati @Levon770 fixed in 93837ff. Cheers!
