### ISSUE TITLE
Could you support JSON value?

### ISSUE THREAD

**Issue by ivancas84** [IliaIdakiev/angular-material-timepicker#33]
Material Angular Datepicker supports JSON values. It is easy to initialize directly from the database. Could you incorporate initialization through a JSON Date value?

For example: when you call:
```typescript
this.control.setValue("2020-09-25T19:00:00-03:00")
```
you get:
```
ERROR TypeError: value.setSeconds is not a function
    at MatTimepickerDirective.writeValue (mat-timepicker.js:917)
```

**Comment by IliaIdakiev** [comment]
@ivancas84 The control expects a Date object and providing a string won't work. You will need to do:
```javascript
this.control.setValue(new Date("2020-09-25T19:00:00-03:00"));
```

**Comment by ivancas84** [comment]
Ah ok. It's simple. Thanks!
