### ISSUE TITLE
Time format problems

### ISSUE THREAD

**Issue by cberenguer** [IliaIdakiev/angular-material-timepicker#35]
Hi, i have this problem with the library, i select for example this hour (5:00 am) and the value return is 2020-11-23T10:00:00.000Z, this is not right need to be 2020-11-23T05:00:00.000Z, you can help me please, thanks

**Comment by IliaIdakiev** [comment]
Hello @cberenguer. Thanks for opening this issue. Can you please provide a [stackblitz](http://stackblitz.com/) with the issue that you are experiencing so I can debug it and resolve it. Thanks.
