### ISSUE TITLE
custom theme problems?

### ISSUE THREAD

**Issue by DerHerrGammler** [IliaIdakiev/angular-material-timepicker#36]
if i provide a custom theme and none of the material default strage things happen to the picker:

![grafik](https://user-images.githubusercontent.com/30802629/102911302-21e19f00-447c-11eb-948c-88479763851c.png)

how can i fix this?

**Comment by IliaIdakiev** [comment]
Hello @DerHerrGammler. Thanks for opening the issue and happy new year! Tbh I haven't played around with using different themes. I will take a look in the next few weeks. Can you send me a [stackblitz](http://stackblitz.com/)  in order to see what you are trying to achieve. Thanks.

**Comment by alexfriesen** [comment]
I have the same issue when overwriting the light theme for dark-mode
```css
@media (prefers-color-scheme: dark) {
     :root {
        @include angular-material-theme($darkTheme);
     }
}
```

**Comment by IliaIdakiev** [comment]
@alexfriesen thanks for commenting and @DerHerrGammler sorry for taking so long but it's been a busy start of the year and I can't find free time to sit down and fix this issue. I haven't forgotten about it and I will try to find time soon.

**Comment by IliaIdakiev** [comment]
c387f1a

**Comment by hennihaus** [comment]
Hello @IliaIdakiev ,

thanks for your pull request. The hour view looks pretty nice now. 

![Screenshot from 2021-04-22 16-33-24](https://user-images.githubusercontent.com/47771386/115732870-a986de00-a388-11eb-84b8-83f4923051b0.png)


**Unfortunately I still have a problem with the minute view.**

![Minute View](https://user-images.githubusercontent.com/47771386/115729003-4fd0e480-a385-11eb-8b34-6a51ef20cc6e.png)

The error comes up when I use a overlay container from angular material.
I hope you can fix it, because you are the only one with a convincing timepicker here for Angular.

**Comment by Neelia99** [comment]
Hello @IliaIdakiev ,

I have the same problem like @hennihaus.
The hour view looks good. 
But I still have the problem with the minute view:
![image](https://user-images.githubusercontent.com/80746378/115735928-274be900-a38b-11eb-97b8-cc6d585732f2.png)

Hopefully you can fix the problem.

**Comment by IliaIdakiev** [comment]
Hello @Neelia99 , please update to the latest version using `npm install mat-timepicker@latest` or `yarn add mat-timepicker@latest`

**Comment by 0Taan0** [comment]
Hello @IliaIdakiev,

I have the same problem as the persons above. When i use an overlay container from Material Design I have the problem that the minute selector gets the same error as above:  
[**Stackblitz Example**](https://stackblitz.com/edit/angular-ivy-7v2vfz?file=src/app/app.component.ts)

![**Error**](https://user-images.githubusercontent.com/80679712/115967035-a29acf80-a530-11eb-86ae-ed21087b6b3c.JPG)

Here I have a Stackblitz example, the error occurs when I try to activate a costum material theme with the overlay container (app.component.ts) per class selector (styles.scss, line 29) :

[**Stackblitz Example**](https://stackblitz.com/edit/angular-ivy-7v2vfz?file=src/app/app.component.ts)

Hopefully you can fix this error.

**Comment by IliaIdakiev** [comment]
Hello @0Taan0, please try mat-timepicker@5.1.4. Thanks
