### ISSUE TITLE
Support anguar 11 ?

### ISSUE THREAD

**Issue by mithleshk** [IliaIdakiev/angular-material-timepicker#38]
While migrating to Angular 11 there is an incompatibility issue with rxjs.

warning: Package "mat-timepicker" has an incompatible peer dependency to "rxjs" (requires "~6.5.4", would install "6.6.3").

**Comment by IliaIdakiev** [comment]
@mithleshk, thanks for opening the issue. The dependencies need to be updated but that it's not a serious problem. You can see that it's just a warning so you can safely use the library with Angular 11. I will update the deps whenever I have some free time. You are also welcome to do so if you wish. I will leave the issue open until then.

**Comment by FloMaetschke** [comment]
Thumps up for angular 12 🍡

**Comment by VladyslavTkach** [comment]
There is already pull request for updating https://github.com/IliaIdakiev/angular-material-timepicker/pull/50

**Comment by Totati** [comment]
And Angular 13 ⚰ Has anybody a recommendation for another lob, with same user experience?
