### ISSUE TITLE
Id collision

### ISSUE THREAD

**Issue by Totati** [IliaIdakiev/angular-material-timepicker#39]
Hello, the MatTimepickerDirective auto genereated 'unique' id may collide with MatInput. It should be renamed to `` `mat-timepicker-${MatTimepickerDirective.nextId++}` `` https://github.com/IliaIdakiev/angular-material-timepicker/blob/master/projects/mat-timepicker/src/lib/timepicker.directive.ts#L127

**Comment by IliaIdakiev** [comment]
@Totati you are right, thanks for noting this. I will fix it right away.

**Comment by IliaIdakiev** [comment]
0be802e
