### ISSUE TITLE
Incorrect time parsing

### ISSUE THREAD

**Issue by martin-havala** [IliaIdakiev/angular-material-timepicker#40]
Hey, I've found one small issue while parsing time 
 

1.  set mode to 12h, no time limit
2. enter 12:05 **am**
3.  time is parsed to 12:05 **pm**

Reproducible here (just adjusted fork from library demo)
https://stackblitz.com/edit/github-kdln6n?file=src/app/app.component.html

**Comment by IliaIdakiev** [comment]
@martin-havala thanks for opening this issue. I will look into that and I will close the issue when a fix is merged,

**Comment by IliaIdakiev** [comment]
e1569f5
