### ISSUE TITLE
mat-form-field-required-marker not showing when matTimepicker is used

### ISSUE THREAD

**Issue by angelaki** [IliaIdakiev/angular-material-timepicker#79]
When using matTimepicker the required markes isn't shown for some reason:

![image](https://user-images.githubusercontent.com/38611461/173822682-c542f716-182e-4523-b861-9f48908e43f7.png)

It works with the `required` attribute but won't work with a required form field.

**Comment by IliaIdakiev** [comment]
@angelaki do you mean whenever you have the required validator inside a reactive form?

**Comment by angelaki** [comment]
Yes, correct. I was just about to create you a minimal repro, but the current versions seams to have an issue: https://stackblitz.com/edit/angular-ivy-dj5fhq?file=package.json,src%2Fapp%2Fapp.module.ts

**Comment by IliaIdakiev** [comment]
@angelaki no worries, I will try to take a look this weekend, cheers

**Comment by angelaki** [comment]
Been some weekends lately 😉 Don't let this nice lib down!

**Comment by IliaIdakiev** [comment]
@angelaki sorry but I'm quite busy, fixed in the new release. Btw the library is open source so PRs are very welcome ;)
