### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by jchapelle** [IliaIdakiev/angular-material-timepicker#80]
Hello, when upgrading to angular 14, some warnings are displayed
Package "mat-timepicker" has an incompatible peer dependency to "@angular/cdk" (requires "^11.2.12", would install "14.0.2").

Would it be possible to solve this ?

**Comment by Dan890** [comment]
There is already pull request for updating https://github.com/IliaIdakiev/angular-material-timepicker/pull/82

**Comment by IliaIdakiev** [comment]
merged
