### ISSUE TITLE
ɵɵFactoryDeclaration issue.

### ISSUE THREAD

**Issue by brykurt** [IliaIdakiev/angular-material-timepicker#86]
I'm having an issue with mat time picker after I run npm install. Please see image below.
![image](https://user-images.githubusercontent.com/21966219/186090401-7a895a54-e6cb-43ae-9972-eaffeb6d23a0.png)

**Comment by IliaIdakiev** [comment]
@brykurt the latest version is for Angular 14, what Angular version are you running?

**Comment by IliaIdakiev** [comment]
@brykurt please follow the steps [here](https://github.com/IliaIdakiev/angular-material-timepicker/issues/87#issuecomment-1224184266) and also check the versions (Node/Angular). I'm closing this issue because I just tested out creating a new project with the library and everything works fine.

**Comment by brykurt** [comment]
Hi sorry for the late reply @IliaIdakiev, already fixed the issue. By the way, what's the ideal time picker version for angular 8?

**Comment by IliaIdakiev** [comment]
You can try with [2.0.0](https://www.npmjs.com/package/mat-timepicker/v/2) but back then the whole timepicker was used differently so I would recommend using the latest version of angular with the current version of the picker
