### ISSUE TITLE
How can I change the font of the dropdown menus when using type="time"?

### ISSUE THREAD

**Issue by TomLBarden** [IliaIdakiev/angular-material-timepicker#89]
I'd like to be able to change the font of the element below:
![image](https://user-images.githubusercontent.com/9220988/190201273-56838fd0-8067-4d3e-a0c6-0c2ec2e0bf47.png)

However, I can't for the life of me access this element in the Chrome dev tools. Whenever I interact with any element on the page, or in the tools, this input closes. I can't find which elements or classes I need to manipulate to change the font styling.

**Comment by IliaIdakiev** [comment]
https://github.com/IliaIdakiev/angular-material-timepicker/blob/e3da33cf2c086e706d20987f6fedae263d8004fa/projects/mat-timepicker/src/lib/timepicker-dialog/timepicker-dialog.component.html#L13

**Comment by TomLBarden** [comment]
Hey, I'm sorry, but applying styling to `.time` or `.time-frame` isn't working. Are you able to give some guidance?

```
::ng-deep {
  .time {
    color: red !important;
  }
  .time-frame {
    color: red !important;
  }
}
```
